# Generated by Django 5.1.6 on 2025-02-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('x_resolution', models.IntegerField()),
                ('y_resolution', models.IntegerField()),
                ('encoding_process', models.CharField(max_length=255)),
                ('resolution_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('color_subsampling', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
