# Generated by Django 5.1.6 on 2025-02-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_imagemetadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='filename',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='metadata',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
